Feat/hot 005/setup tailwind navbar
hotosm/website pull request #8
Opened 2024-01-15 12:46 UTC by katporks

This PR introduces the configuration of Tailwind CSS and Alpine.js to construct the header component. Alpine.js variables, defined within `header.html`, are accessible in nested templates due to their initialization in the parent component `header`. It's important to note that Alpine.js operates entirely on the client-side, in the browser, and interacts with the HTML after Django's server-side rendering is complete.

The header component includes the following variables:

- `isMenuOpen`: This variable indicates the state of the mobile hamburger menu, determining whether the mobile navigation should be displayed.
- `isSearchClicked`: This variable controls the visibility of the search modal upon clicking the search icon.

This PR lays the groundwork for the header and navigation. In a subsequent PR, once the site map's links are finalized, I plan to incorporate submenus for the parent links in both the desktop and mobile navigation.

Desktop header:
<img width="1139" alt="Desktop header" src="https://github.com/hotosm/website/assets/59626759/7842fe9f-7d2b-4751-a0d6-4aef48af5233">

Mobile header:
<img width="561" alt="Mobile header" src="https://github.com/hotosm/website/assets/59626759/868ed137-e317-4b6a-9310-9ac64835ee1d">

2024-01-15 21:56 UTC, JoltCode commented
Thanks Kat! Will take a look too 👍

2024-01-15 22:25 UTC, JoltCode requested changes
Great work! Just a few CSS changes I'd suggest 👍 - I haven't actually looked at the server in my browser, I don't have the tasking manager website set up.

2024-01-15 22:25 UTC, JoltCode commented on frontend/tailwind.config.js
> +        },
Why are we using pt?

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/branded_elements/button.html
> +<button class="font-medium font-barlow h-hot-4 text-base-18 bg-hot-red text-hot-white px-hot-3 rounded-8 border-2pt border-transparent hover:bg-hot-off-white hover:text-hot-red focus:bg-transparent f
Why do we have a transparent border here? - also related to the comment on using pt :)

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/branded_elements/link.html
> +        <span class="absolute translate-y-[-15%] translate-x-1">⌄</span>
Don't use absolute here, use padding instead - also with the translate, you can make it negative in tailwind by appending a `-` at the start 👍

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/mobile/mobile_menu_button.html
> +    <span class="absolute -inset-0.5"></span>
What's this for?

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/mobile/mobile_menu_link.html
> +        <span class="absolute translate-y-[-15%] translate-x-1">⌄</span>
And an aria text label here :)

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/mobile/mobile_navigation.html
> +    <nav class="space-y-1 pb-3 pt-2 font-medium text-base-18"
Use `gap` - it's cleaner, and doesn't introduce margins on children, rather it adds gaps between children at the flexbox parent level 👍

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/mobile/mobile_navigation.html
> +        <ul class="space-y-0.5 list-none pl-0">
^ - gap :)

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/nav/primary_desktop_nav.html
> +        <ul class="flex text-base-18 p-0 flex-row space-x-4 mt-0 border-0"
^ - gap :)

2024-01-15 22:25 UTC, JoltCode commented on hot_osm/templates/components/branded_elements/social_icons.html
> +<ul class="flex flex-shrink-0 h-hot-2 space-x-1.5">
^ - gap :)

2024-01-18 12:59 UTC, spwoodcock approved these changes
Looks great - nice use of Tailwind / CSS!

@JoltCode may have a better idea how to fix the custom spacing and breakpoint issue 😄 

The great thing is that Alpine.js works nicely with Web Components, so hopefully integrating them shouldn't be too big of a refactor:
- Any logic encapsulated in the Web Component can replace the alpine.js equivalent.
- Anything missing from the Web Component logic can be supplemented by alpine.js easily.

2024-01-18 13:08 UTC, JoltCode commented on frontend/tailwind.config.js
> +          "nav-breakpoint": "1050px", // prevents nav  links from wrapping into two lines
Could we use `lg:` instead? It's pretty close to the default tailwind `1024px` breakpoint :)

2024-01-18 13:12 UTC, JoltCode commented on hot_osm/templates/components/branded_elements/social_icons.html
> +        <a href="https://www.facebook.com/hotosm" aria-label="Facebook">
Good stuff on all these aria labels! 😄

2024-01-18 13:14 UTC, JoltCode commented on hot_osm/templates/components/mobile/mobile_menu_link.html
> +   class="block font-medium font-barlow text-hot-black py-2 pl-3 pr-4 border-l-4 text-base {% if selected|default:False %}border-hot-red bg-hot-light-grey text-hot-red {% else %} border-transparent h
Does the `hover:border-gray-300` need to be changed to a HOT colour?

2024-01-18 13:15 UTC, JoltCode commented on hot_osm/templates/components/mobile/mobile_navigation.html
> +    <nav class="border-t border-b border-gray-200 py-2">
Again just checking if we're good to use the tailwindcss colours, not the HOT colours for these borders 👍

2024-01-18 13:18 UTC, JoltCode commented
> Looks great - nice use of Tailwind / CSS!
> 
> @JoltCode may have a better idea how to fix the custom spacing and breakpoint issue 😄
> 
> The great thing is that Alpine.js works nicely with Web Components, so hopefully integrating them shouldn't be too big of a refactor:
> 
> * Any logic encapsulated in the Web Component can replace the alpine.js equivalent.
> * Anything missing from the Web Component logic can be supplemented by alpine.js easily.

Sure thing! What're the specific issues we're facing? - Feel free to PM about this! 😄

2024-01-19 05:32 UTC, merged